name: faved
services:
  apache-php:
    container_name: faved-web-app
    build: .
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./apache-conf:/etc/apache2/sites-enabled
    ports:
      - "${PORT:-8000}:80"

